# Generated by Django 4.0.2 on 2022-10-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_anulate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('image', models.ImageField(upload_to=None, verbose_name='Imagen')),
                ('categorys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.categoria')),
            ],
        ),
    ]
