# Generated by Django 4.0.2 on 2022-10-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categorys',
            new_name='categorias',
        ),
    ]
