# Generated by Django 4.0.2 on 2022-11-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_carrito_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
